services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright_automation
    env_file:
      - .env
    environment:
      - CI=true
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      - ./allure-results:/app/allure-results
      - ./.auth:/app/.auth
